language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - USE_OPTIONAL=true
  - USE_OPTIONAL=false

before_install:
  - git submodule update --init --recursive

install:
  - bash requirements-install.sh

script:
  - py.test
  - bash flake8-run.sh

after_script:
  - python debug-info.py
